### ISSUE TITLE
Documents and more information ?

### ISSUE THREAD

**Issue by zoro238** [mbramwell1/GeoFire-Android#16]
I find a lot of information missing in the documents
Such as radius work around the user.
and 
2-Retrieving a location
3-Geo Queries
4-GeoQueryEventListener 
5-Data Events
6-Updating the query criteria (setCenter ,setRadius)
and other

**Comment by mbramwell1** [comment]
Hey Zoro,

This library is currently version 0.0.2. I must stress that it is NOT production ready.

To address some of those points however:

1. If you want to search radius around the user, simply set your QueryLocation to be the coordinates of the user using Googles location libraries.
2. I dont know what you mean by this? If you want some kind of map functionality or location search i.e. google maps, use google maps. If you want to search by radius of a location then GeoFire is ideal.
3. Again I'm not sure what you mean. GeoFire uses documents you have stored in Firestore, and queries them based on a radius of coordinates that you supply.
4. GeoQueryEventListener? I have no idea what you mean. Again I must state that this is NOT a geo lookup library. It has a very specific use case.
5. Data Events in what way?
5. If you want to update the query criteria, create a new Query object.... `QueryLocation queryLocation = QueryLocation.fromDegrees(latitude, longitude);
Distance searchDistance = new Distance(1.0, DistanceUnit.KILOMETERS);`
